name: releaseAndBuildArmDockerImage

on:
  release:
    types: [published]

jobs:
  build_and_release:
    name: Build, Package and Push ARM Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set Tag Variable
        id: vars
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Set up Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.21.1'
      
      - name: Ensure dependencies
        run: go mod tidy

      # === Build arm64 package ===
      - name: Build arm64 binary package
        run: |
          chmod +x ./build/cmd/package.sh
          ./build/cmd/package.sh ${{ steps.vars.outputs.tag }} arm64
          ls -l ./out/

      # === Prepare Docker resources ===
      - name: Copy arm64 package to Docker resources
        run: cp ./out/apinto_${{ steps.vars.outputs.tag }}_linux_arm64.tar.gz ./build/resources/apinto.linux.arm64.tar.gz

      # === Setup docker buildx and login ===
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # === Build & push multi-arch docker image ===
      - name: Build and push multi-architecture docker image
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -t ${{ secrets.DOCKER_USERNAME }}/apinto-gateway:${{ steps.vars.outputs.tag }} \
            --push \
            -f ./build/resources/Dockerfile ./build/resources

      # === Push latest tag ===
      - name: Tag and push latest image
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -t ${{ secrets.DOCKER_USERNAME }}/apinto-gateway:latest \
            --push \
            -f ./build/resources/Dockerfile ./build/resources
